trigger:
  - main # Trigger pipeline on changes to the 'main' branch

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: Build
        displayName: "Build Job"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            submodules: true
            persistCredentials: true
          - script: |
              sudo apt-get update
              sudo apt-get install -y zip
            displayName: "Install ZIP Utility"
          - script: |
              cd Lab_4
              npm install
              zip -r $(System.DefaultWorkingDirectory)/Lab_4/functionApp.zip *
            displayName: "Install Dependencies and Package App"
          - script: |
              ls -lh $(System.DefaultWorkingDirectory)/Lab_4/functionApp.zip
            displayName: "Verify ZIP File"
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: "$(System.DefaultWorkingDirectory)/Lab_4/functionApp.zip"
              artifactName: "functionAppArtifact"
              publishLocation: "Container"
            displayName: "Publish Build Artifact"

  - stage: Test
    displayName: "Test Stage"
    dependsOn: Build # Ensure this stage runs after Build
    jobs:
      - job: Test
        displayName: "Test Job"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - script: |
              cd Lab_4
              npm test
            displayName: "Run Unit Tests"

  - stage: Deploy
    displayName: "Deploy Stage"
    jobs:
      - job: Deploy
        displayName: "Deploy Job"
        pool:
          vmImage: "windows-latest"
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: "functionAppArtifact"
              targetPath: "$(System.DefaultWorkingDirectory)"
            displayName: "Download Build Artifact"
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: "assignment4" # Replace with the correct service connection name
              appName: "ass4" # Replace with your Azure Function App name
              package: "$(System.DefaultWorkingDirectory)/Lab_4/functionApp.zip"
