trigger:
  - main # Trigger pipeline on changes to the 'main' branch

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: Build
        displayName: "Build Job"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - script: |
              npm install
            displayName: "Install Dependencies"

  - stage: Test
    displayName: "Test Stage"
    dependsOn: Build # Ensure this stage runs after Build
    jobs:
      - job: Test
        displayName: "Test Job"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - script: |
              npm test
            displayName: "Run Unit Tests"

  - stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Test
  jobs:
    - job: Deploy
      displayName: "Deploy Job"
      pool:
        vmImage: "windows-latest"
      steps:
        - task: AzureFunctionApp@1
          inputs:
            azureSubscription: "MyAzureServiceConnection"  # Replace with the correct service connection name
            appName: "YourFunctionAppName"                 # Replace with your Azure Function App name
            package: "$(Build.ArtifactStagingDirectory)/**/*.zip"
