trigger:
  - main # Trigger pipeline on changes to the 'main' branch

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: Build
        displayName: "Build Job"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - script: |
              cd Lab_4
              npm install
              zip -r functionApp.zip * # Package the app into a zip file
            displayName: "Install Dependencies and Package App"
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: "$(System.DefaultWorkingDirectory)/Lab_4/functionApp.zip"
              artifactName: "functionAppArtifact"
              publishLocation: "Container"
            displayName: "Publish Build Artifact"

  - stage: Test
    displayName: "Test Stage"
    dependsOn: Build # Ensure this stage runs after Build
    jobs:
      - job: Test
        displayName: "Test Job"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - script: |
              cd Lab_4
              npm test
            displayName: "Run Unit Tests"

  - stage: Deploy
    displayName: "Deploy Stage"
    dependsOn: Test # Ens
